package horse.sumomo.pos_doc_backend.ingestion.testsupport;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * One-shot utility to regenerate the committed whole-stack test fixture
 * with real PDFs generated by {@link SyntheticPdfFactory}. Run via:
 * <pre>
 *   mvnw test-compile exec:java -Dexec.mainClass=...
 * </pre>
 * or simply call {@link #main} from a test.
 */
public final class FixtureRegenerator {

	private FixtureRegenerator() {
	}

	public static void main(String[] args) throws IOException {
		Path out = Path.of("src/test/resources/fixtures/valid-two-pdf.zip");
		byte[] pdfA = SyntheticPdfFactory.createPdf("Doc A");
		byte[] pdfB = SyntheticPdfFactory.createPdf("Doc B");

		try (ZipOutputStream zip = new ZipOutputStream(new FileOutputStream(out.toFile()))) {
			ZipEntry e1 = new ZipEntry("documents/first.pdf");
			e1.setTime(0);
			zip.putNextEntry(e1);
			zip.write(pdfA);
			zip.closeEntry();

			ZipEntry e2 = new ZipEntry("documents/second.pdf");
			e2.setTime(0);
			zip.putNextEntry(e2);
			zip.write(pdfB);
			zip.closeEntry();
		}
		System.out.println("Wrote " + out.toAbsolutePath() + " (" + Files.size(out) + " bytes)");
	}

}
