package horse.sumomo.pos_doc_backend.ingestion.archive;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards the committed whole-stack fixture
 * {@code src/test/resources/fixtures/valid-two-pdf.zip} against accidental
 * (or malicious) replacement.
 *
 * <p>The fixture's SHA-256 is pinned here. If the binary is regenerated or
 * edited, the hash changes and this test fails, forcing a deliberate review.
 * The fixture is regenerated by {@code scripts/make-fixture.py}, which
 * asserts the same hash.
 *
 * <p>Expected SHA-256 of {@code valid-two-pdf.zip}:
 * <pre>
 * bc193644e5e9b4254c5476b3f254178260a94c37359c43974c2286f41c30c9c0
 * </pre>
 */
class FixtureIntegrityTest {

	private static final String EXPECTED_SHA256 = "bc193644e5e9b4254c5476b3f254178260a94c37359c43974c2286f41c30c9c0";
	private static final String FIXTURE = "fixtures/valid-two-pdf.zip";

	@Test
	void committedFixtureMatchesExpectedSha256() throws Exception {
		try (InputStream in = FixtureIntegrityTest.class.getClassLoader().getResourceAsStream(FIXTURE)) {
			assertNotNull(in, "the committed fixture must be on the test classpath: " + FIXTURE);
			String actual = sha256(in);
			assertEquals(EXPECTED_SHA256, actual,
					"the committed fixture has been altered; regenerate with scripts/make-fixture.py and review the diff");
			assertTrue(actual.length() == 64, "a SHA-256 hex digest is 64 characters");
		}
	}

	@Test
	void fixtureContainsTwoRenderablePdfs() throws Exception {
		try (InputStream in = FixtureIntegrityTest.class.getClassLoader().getResourceAsStream(FIXTURE)) {
			assertNotNull(in, "the committed fixture must be on the test classpath: " + FIXTURE);
			try (ZipInputStream zis = new ZipInputStream(in)) {
				ZipEntry entry;
				int count = 0;
				while ((entry = zis.getNextEntry()) != null) {
					assertTrue(entry.getName().startsWith("documents/"),
							"unexpected ZIP entry: " + entry.getName());
					byte[] pdfBytes = zis.readAllBytes();
					try (PDDocument doc = org.apache.pdfbox.Loader.loadPDF(pdfBytes)) {
						assertFalse(doc.isEncrypted(),
								"fixture PDF must not be encrypted: " + entry.getName());
						assertTrue(doc.getNumberOfPages() >= 1,
								"fixture PDF must have at least one page: " + entry.getName());
						PDFRenderer renderer = new PDFRenderer(doc);
						BufferedImage image = renderer.renderImage(0);
						assertNotNull(image, "page 0 must render to an image: " + entry.getName());
						assertTrue(image.getWidth() > 0 && image.getHeight() > 0,
								"rendered image must have non-zero dimensions: " + entry.getName());
					}
					count++;
				}
				assertEquals(2, count, "fixture must contain exactly two PDF entries");
			}
		}
	}

	private static String sha256(InputStream in) throws IOException {
		try {
			MessageDigest digest = MessageDigest.getInstance("SHA-256");
			byte[] buffer = new byte[8192];
			int n;
			while ((n = in.read(buffer)) != -1) {
				digest.update(buffer, 0, n);
			}
			return HexFormat.of().formatHex(digest.digest());
		}
		catch (NoSuchAlgorithmException e) {
			throw new IllegalStateException("SHA-256 is required but unavailable", e);
		}
	}

}
