package horse.sumomo.pos_doc_backend.ingestion.archive;

import java.io.IOException;
import java.io.InputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards the committed whole-stack fixture
 * {@code src/test/resources/fixtures/valid-two-pdf.zip} against accidental
 * (or malicious) replacement.
 *
 * <p>The fixture's SHA-256 is pinned here. If the binary is regenerated or
 * edited, the hash changes and this test fails, forcing a deliberate review.
 * The fixture is regenerated by {@code scripts/make-fixture.py}, which
 * asserts the same hash.
 *
 * <p>Expected SHA-256 of {@code valid-two-pdf.zip}:
 * <pre>
 * 1ce96e72137fd1b084410d8f1f9154bce9dfd435fc9e9ab6a8ea340968e362a0
 * </pre>
 */
class FixtureIntegrityTest {

	private static final String EXPECTED_SHA256 = "1ce96e72137fd1b084410d8f1f9154bce9dfd435fc9e9ab6a8ea340968e362a0";
	private static final String FIXTURE = "fixtures/valid-two-pdf.zip";

	@Test
	void committedFixtureMatchesExpectedSha256() throws Exception {
		try (InputStream in = FixtureIntegrityTest.class.getClassLoader().getResourceAsStream(FIXTURE)) {
			assertNotNull(in, "the committed fixture must be on the test classpath: " + FIXTURE);
			String actual = sha256(in);
			assertEquals(EXPECTED_SHA256, actual,
					"the committed fixture has been altered; regenerate with scripts/make-fixture.py and review the diff");
			assertTrue(actual.length() == 64, "a SHA-256 hex digest is 64 characters");
		}
	}

	private static String sha256(InputStream in) throws IOException {
		try {
			MessageDigest digest = MessageDigest.getInstance("SHA-256");
			byte[] buffer = new byte[8192];
			int n;
			while ((n = in.read(buffer)) != -1) {
				digest.update(buffer, 0, n);
			}
			return HexFormat.of().formatHex(digest.digest());
		}
		catch (NoSuchAlgorithmException e) {
			throw new IllegalStateException("SHA-256 is required but unavailable", e);
		}
	}

}
