"""Regenerate the committed whole-stack test fixture and verify its hash.

The fixture at ``src/test/resources/fixtures/valid-two-pdf.zip`` contains
two genuine, deterministic one-page PDFs generated by
``SyntheticPdfFactory`` (PDFBox). The ZIP entry names are:

    documents/first.pdf
    documents/second.pdf

Usage (from the repository root):

    python scripts/make-fixture.py

This script delegates PDF generation to the Java ``FixtureRegenerator``
class (run via Maven exec) and then verifies the resulting SHA-256.
"""
import hashlib
import os
import subprocess
import sys

# The committed fixture must produce exactly this SHA-256.
EXPECTED_SHA256 = "bc193644e5e9b4254c5476b3f254178260a94c37359c43974c2286f41c30c9c0"

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO_ROOT, 'src', 'test', 'resources', 'fixtures', 'valid-two-pdf.zip')


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def main():
    # Compile test classes (needed for FixtureRegenerator + SyntheticPdfFactory).
    print("Compiling test classes...")
    subprocess.run(
        ['mvnw.cmd' if os.name == 'nt' else './mvnw', 'test-compile', '-q'],
        cwd=REPO_ROOT, check=True,
    )

    # Run FixtureRegenerator to produce the ZIP with real PDFs.
    print("Generating fixture via FixtureRegenerator...")
    subprocess.run(
        ['mvnw.cmd' if os.name == 'nt' else './mvnw', '-q', 'exec:java',
         '-Dexec.mainClass=horse.sumomo.pos_doc_backend.ingestion.testsupport.FixtureRegenerator',
         '-Dexec.classpathScope=test'],
        cwd=REPO_ROOT, check=True,
    )

    actual = sha256_of(OUT)
    if actual != EXPECTED_SHA256:
        print(f"ERROR: fixture SHA-256 mismatch.\n"
              f"  expected: {EXPECTED_SHA256}\n"
              f"  actual:   {actual}", file=sys.stderr)
        sys.exit(1)
    print(f"OK: fixture SHA-256 = {actual}")


if __name__ == '__main__':
    main()
